language: python
sudo: False
matrix:
  include:
    - python: "2.6"
      env: REQUIREMENTS=python2_test_requirements.txt
    - python: "2.7"
      env: REQUIREMENTS=python2_test_requirements.txt
    - python: "pypy"
      env: REQUIREMENTS=python2_test_requirements.txt
    - python: "3.2"
      env: REQUIREMENTS=python3_test_requirements.txt
    - python: "3.3"
      env: REQUIREMENTS=python3_test_requirements.txt
    - python: "3.4"
      env: REQUIREMENTS=python3_test_requirements.txt
    - python: "pypy3"
      env: REQUIREMENTS=python3_test_requirements.txt

install:
  - pip install -r $REQUIREMENTS
  - python setup.py develop
script:
  - coverage run -m haas -v
  - coverage report -m

after_success:
  - coveralls
