language: python
sudo : false
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "pypy"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "pypy3"
cache:
  - pip
install:
  - pip install --upgrade pip
  - pip install -r travis-ci-requirements.txt
  - pip install -e .
script:
  - coverage run -m haas -v
after_success:
  - pip install codecov
  - codecov
