language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ; fi
  - pip install haas
  - pip install coverage
  - pip install coveralls

script:
  - coverage run -m haas -v
  - coverage report -m

after_success:
  - coveralls
